version: '3.2'
services:
  redis:
    container_name: nightlight-redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  backend:
    container_name: nightlight-backend
    image: nightlight.azurecr.io/nightlight-backend
    restart: always
    ports:
      - 6060:6060
    links:
      - redis:redis
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/nightlight-backend