# This workflow will run the Jest tests
name: Backend Testing

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 6s
          --health-timeout 5s
          --health-retries 5
          --name redis

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run CI
        run: npm ci

      - name: Run Build
        run: npm run build --if-present

      - name: Start Worker
        run: npm run worker &
        env:
          WORKER_PID: $!
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Wait for Redis
        run: |
          echo "Waiting for Redis to become healthy..."
          while [[ "$(docker inspect -f '{{.State.Health.Status}}' redis)" != "healthy" ]]; do sleep 1; done
          echo "Redis is now healthy."

      - name: Run Server and Test
        run: |
          sleep 3
          npm test
        env:
          REDIS_HOST: redis
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Stop Worker
        run: kill $WORKER_PID || true
