# This workflow will run the Jest tests
name: Backend Testing

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  start-worker:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 6s
          --health-timeout 5s
          --health-retries 5
          --name redis

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Worker
        run: npm run worker
        env:
          WORKER_PID: $!
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

  test-backend:
    needs: start-worker
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 6s
          --health-timeout 5s
          --health-retries 5
          --name redis

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run CI
        run: npm ci

      - name: Run Build
        run: npm run build --if-present

      - name: Run Server and Test
        run: |
          sleep 3
          npm test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
