name: Trigger auto deployment for nightlight-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nightlight-backend-AutoDeployTrigger-5e374186-fdb5-4d81-aaa8-a9fc13c690c0.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: nightlight.azurecr.io
          username: ${{ secrets.NIGHTLIGHTBACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.NIGHTLIGHTBACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nightlight.azurecr.io/nightlight-backend:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NIGHTLIGHTBACKEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n nightlight-backend -g nightlight-app --server nightlight.azurecr.io --username  ${{ secrets.NIGHTLIGHTBACKEND_REGISTRY_USERNAME }} --password ${{ secrets.NIGHTLIGHTBACKEND_REGISTRY_PASSWORD }}
            az containerapp update -n nightlight-backend -g nightlight-app --image nightlight.azurecr.io/nightlight-backend:${{ github.sha }}
